---
  - name: installing and launching metricbeat
    hosts: webservers
    become: yes
    tasks:

      - name: download metric deb
        command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

      - name: use dpkg to install the file
        command: dpkg -i metricbeat-7.4.0-amd64.deb

      - name: copy the metricbeat config file
        copy:
          src: /etc/metricbeat/metricbeat.yml
          dest: /etc/metricbeat/metricbeat.yml

      - name: enable and configure system module
        command: metricbeat modules enable docker

      - name: setup metricbeat
        command: metricbeat setup

      - name: start metricbeat
        command: service metricbeat start
        
      - name: enable metricbeat
        systemd:
          name: metricbeat
          enabled: yes